version: '3.9'

services:
  go-app:
    container_name: go-app
    image: mik3asg/go-app:1.0
    build: .
    environment:
      DATABASE_URL: "host=go-db user=${POSTGRES_USER} password=${POSTGRES_PASSWORD} dbname=${POSTGRES_DB} sslmode=disable"     
    ports:
      - "8000:8000"
    depends_on:
      - go-db
  go-db:
    container_name: go-db
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
